### ISSUE TITLE
UnixSocketEnvVar should contain the whole path to the database's socket

### ISSUE THREAD

**Issue by hessjcg** [GoogleCloudPlatform/cloud-sql-proxy-operator#125]
## Expected Behavior
When you use this configuration: 
```
apiVersion: cloudsql.cloud.google.com/v1alpha1
kind: AuthProxyWorkload
metadata:
  name: authproxyworkload-sample
spec:
  authProxyContainer:
    image: "gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.0.0-preview.2"
  workloadSelector:
    kind: "Deployment"
    name: "gke-cloud-sql-app"
  instances:
    - connectionString: "my-project:us-central1:my-instance"
      unixSocketPathEnvName: "DB_SOCKET_PATH"
      socketType: "unix"
      unixSocketPath: "/csql/pg"
```

Then the value of DB_SOCKET_PATH should be `/csql/pg/my-project:us-central1:my-instance/.s.PGSQL.5432` the full path to the postgres unix socket file.

For other database types, the DB_SOCKET_PATH should be the full path to the unix socket file as well.

The operator should make sure that this is true, regardless of database type or particular implementation in the proxy.

## Actual Behavior

Then the value of DB_SOCKET_PATH is set to `/csql/pg`
