### ISSUE TITLE
Missing namespace selector

### ISSUE THREAD

**Issue by pocesar** [GoogleCloudPlatform/cloud-sql-proxy-operator#467]
## Expected Behavior
Provide a namespace and select the resources

## Actual Behavior
Can't provide a namespace and it seems to be defaulting to `default`

## Steps to Reproduce the Problem

1. Create a deployment at any namespace that isn't default
2. Install the operator
3. Deploy the AuthProxyWorkload with a kind + name or kind + selector

Looking at the logs, it's hardcoding default there:

> 2023-10-18T00:42:28Z	INFO	Reconcile loop started AuthProxyWorkload	{"controller": "authproxyworkload", "controllerGroup": "cloudsql.cloud.google.com", "controllerKind": "AuthProxyWorkload", "AuthProxyWorkload": {"name":"x-proxy","namespace":"default"}, "namespace": "default", "name": "x-proxy", "reconcileID": "53e181bc-cfcf-46c7-9e22-2458d1f08e75", "name": {"name":"x-proxy","namespace":"default"}}

An alternative would be to set the `AuthProxyWorkload` namespace itself to match the current desired namespace but this will generate a lot of duplicates of the same configuration across multiple namespaces

## Specifications

- Version: 1.2.0
- Platform: GKE Autopilot

**Comment by hessjcg** [comment]
Hi @pocesar,  I understand the frustration of needing to create the same AuthProxyWorkload in each namespace. 

However, omitting `namespace` was an intentional choice for security. The AuthProxyWorkload  resource can only add proxy containers to the workloads in the same namespace. This efficiently prevents privilege escalation.

Suppose you have a multi-tenant kubernetes cluster. Alice may only create resources in the 'alice-ns'. Bob may only create resources in the 'bob-ns' namespaces. Alice is a bad actor, and wants to break Bob's web application, so she creates this AuthProxyWorkload: 

```yaml
apiVersion: cloudsql.cloud.google.com/v1
kind: AuthProxyWorkload
metadata:
  name: authproxyworkload-sample
  namespace: alice-ns
spec:
  workloadSelector:
    kind: "Deployment" 
    name: "bob-webapp" 
    namespace: "bob-ns"
  instances:
    - connectionString: "no-project:us-central1:does-not-exist" # This instance doesn't exist, so the proxy container will fail.
```

Because the operator only allows AuthProxyWorkload to affect pods in the same namespace, Bob's web application is safe from Alice's attack.
