### ISSUE TITLE
A way to create 1 instance for every n pods

### ISSUE THREAD

**Issue by pocesar** [GoogleCloudPlatform/cloud-sql-proxy-operator#482]
We are currently scaling up and down using spot instances (1000's) and the overhead of 2GB is really showing, almost defeating the purpose of using spot instances. 
Ideally the operator should see how many pods are currently there and create a rule for 1 proxy pod for every n pods (that you can set), say, 40 connections per pod and distribute accordingly.

**Comment by enocom** [comment]
Typically we recommend customers run the Proxy on the same pod as their workload. Otherwise, there's a risk of cross VM traffic that isn't encrypted by the Proxy.

What if we added support for configuring resource limits instead? 2GB is really just a ballpark starting point and not necessarily the right value for every workload.

**Comment by hessjcg** [comment]
You can already configure the resource limits on the proxy container. This is a snippet from [docs/examples/deployment-postgres-tcp.yaml]( https://github.com/GoogleCloudPlatform/cloud-sql-proxy-operator/main/docs/examples/deployment-postgres-tcp.yaml) showing how to reduce the resource limits on the proxy container pod. 

```
apiVersion: cloudsql.cloud.google.com/v1
kind: AuthProxyWorkload
metadata:
  name: authproxyworkload-sample
spec:
  authProxyContainer:
    # Resource configuration depends on an application's requirements. You
    # should adjust the following values based on what your application
    # needs. For details, see https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
    resources:
      requests:
        # The proxy's CPU use scales linearly with the amount of IO between
        # the database and the application. Adjust this value based on your
        # application's requirements.
        cpu: "0.25"
        # The proxy's memory use scales linearly with the number of active
        # connections. Fewer open connections will use less memory. Adjust
        # this value based on your application's requirements.
        memory: "512Mi"
  workloadSelector:
    kind: "Deployment" # Applies to a "Deployment"
    name: "gke-cloud-sql-app" # named 'gke-cloud-sql-app'
  instances:
    - connectionString: "my-project:us-central1:instance" # from your Cloud SQL Database instance
      portEnvName: "DB_PORT" # Will set an env var named 'DB_PORT' to the database port
      hostEnvName: "DB_HOST" # Will set an env var named 'DB_HOST' to the proxy's host, 127.0.0.1

```

Alternatively, you could run the proxy as a deployment with a service. This is described in the [k8s service example](https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/597b304b7d506a8a88b3f6d2f9be747c7576a133/examples/k8s-service/README.md) in the cloud-sql-proxy repo. This would allow you to scale the proxy pods independently from the application pods. 

Here's how you would adapt that example to let the operator apply the proxy pod to the PGBouncer deployment. 

- Remove the cloud-sql-proxy container from the [pgbouncer_deployment.yaml](https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/597b304b7d506a8a88b3f6d2f9be747c7576a133/examples/k8s-service/pgbouncer_deployment.yaml). 
- Add an AuthProxyWorkload resource that adds the proxy to your pgbouncer_deployment
