### ISSUE TITLE
Feature request: Support for using database connection string (URI)

### ISSUE THREAD

**Issue by hammadzz** [GoogleCloudPlatform/cloud-sql-proxy-operator#551]
I have an application that is configured using a database connection string of format:
DB_CONNECTION_STRING=postgresql://[user[:password]@][netloc][:port][/dbname]

From my reading of the documentation currently there is no way to use a template in the environment variable so that the operator could set the environment variable such as DB_CONNECTION_STRING="postgresql://user:pass@${DB_HOST}:${DB_PORT}/mydb".

Is the current workaround to just hardcode port 5000 and host as 127.0.0.1? How risky is this to go wrong? I would figure it would be okay as long as port 5000 is available.

**Comment by hessjcg** [comment]
Hi @hammadzz,

It sounds like your application expects the environment variable DB_CONNECTION_STRING.  And you want to make sure that the host and port that you hardcode into DB_CONNECTION_STRING will always reflect the host and port configured by the operator. 

Here's how you do that:   

Host will always be `127.0.0.1`.  It is safe to hardcode this in your connection string. 

Port may be explicitly set in the`AuthProxyWorkload` resource. This is better than assuming that operator will choose 5000 for the default port.  Here's an example of a proxy with an explicit port number:

```yaml
apiVersion: cloudsql.cloud.google.com/v1
kind: AuthProxyWorkload
metadata:
  name: authproxyworkload-sample
spec:
  authProxyContainer:
    # Resource configuration depends on an application's requirements. You
    # should adjust the following values based on what your application
    # needs. For details, see https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
    resources:
      requests:
        # The proxy's CPU use scales linearly with the amount of IO between
        # the database and the application. Adjust this value based on your
        # application's requirements.
        cpu: "1"
        # The proxy's memory use scales linearly with the number of active
        # connections. Fewer open connections will use less memory. Adjust
        # this value based on your application's requirements.
        memory: "2Gi"
  workloadSelector:
    kind: "Deployment" # Applies to a "Deployment"
    name: "gke-cloud-sql-app" # named 'gke-cloud-sql-app'
  instances:
    - connectionString: "my-project:us-central1:instance" # from your Cloud SQL Database instance
      port: 5000. # Explicitly set the port for this database instance.
```

Unfortunately, writing arbitrary environment variables from a template has too many edge cases. For example, the database password is a sensitive secret which is not available to the operator. We don't plan to implement this feature.

I hope this example helps you get your applications running reliably. 

-Jonathan
